inherit_from: .robocop_todo.yml

AllCops:
  Exclude:
    - db/**/*

# classやmoduleの先頭コメント    
Documentation:
  Enabled: false

# 日本語でのコメント    
Style/AsciiComments:
  Enaibled: false
# 行長   
Metrics/LineLength:
  Max: 120
# ブロック内の行数 
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*